apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
        - name: application-pod
          image: dactien020796/self-learn
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
