# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build flow for development pharse

on:
  pull_request:
    branches: [ main ]

env:
  JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    # Package and UTs
    - name: Build with Maven
      run: mvn clean package
    # Build and push to JFrog
    - name: Build and push snapshot jar to JFrog Snapshot Repository
      run: |
        ./mvnw -s settings.xml -U \
          -DskipTests=true \
          -DuniqueVersion=false clean deploy
